name: bus_payment_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.4+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  webview_flutter: ^4.2.2
  http: ^0.13.6
  device_info_plus: ^9.1.1
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  geolocator: ^11.0.2
  audioplayers: ^5.2.1
  # install_plugin: ^2.1.0
  install_plugin:
    path: plugins/install_plugin
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  overlay_support: ^2.1.0
  package_info_plus: ^8.3.1
  
dependency_overrides:
  install_plugin:
    path: plugins/install_plugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  overlay_support: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/app_icon.png
    - assets/sounds/complete.mp3
    - assets/sounds/incomplete.mp3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

  
